# Generated by Django 5.1.1 on 2024-09-28 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('img', models.ImageField(default='static/images/70586.jgp', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('other_titles', models.CharField(max_length=250, unique=True)),
                ('connect', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NW', 'New'), ('AC', 'Accepted'), ('PN', 'Pending'), ('RJ', 'REJECTED')], default='1A', max_length=2)),
                ('winter_level', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2A', '2A'), ('2Б', '2Б'), ('3A', '3A'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('spring_level', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2A', '2A'), ('2Б', '2Б'), ('3A', '3A'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('summer_level', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2A', '2A'), ('2Б', '2Б'), ('3A', '3A'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('autumn_level', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2A', '2A'), ('2Б', '2Б'), ('3A', '3A'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tbase.coord')),
                ('photo_img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tbase.image')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbase.users')),
            ],
        ),
    ]
